-- MySQL Script generated by MySQL Workbench
-- vie 04 dic 2015 18:18:52 CST
-- Model: New Model    Version: 1.0
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema FiscoFlex
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `FiscoFlex` DEFAULT CHARACTER SET latin1 ;
USE `FiscoFlex` ;

-- -----------------------------------------------------
-- Table `FiscoFlex`.`ConfiguracionPerfiles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `FiscoFlex`.`ConfiguracionPerfiles` (
  `idConfiguracionPerfil` INT(11) NOT NULL,
  `IdAccion` INT(11) NULL DEFAULT NULL,
  `IdPerfil` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`idConfiguracionPerfil`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `FiscoFlex`.`ConfiguracionesGlobales`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `FiscoFlex`.`ConfiguracionesGlobales` (
  `IdConfiguracionGlobal` VARCHAR(120) NOT NULL,
  `Valor` VARCHAR(50) NULL DEFAULT NULL,
  PRIMARY KEY (`IdConfiguracionGlobal`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `FiscoFlex`.`CuentasContables`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `FiscoFlex`.`CuentasContables` (
  `IdCuentaContable` INT(11) NOT NULL,
  `NombreCuenta` VARCHAR(50) NULL DEFAULT NULL,
  `CuentaPadre` INT(11) NULL DEFAULT NULL,
  `Naturaleza` VARCHAR(80) NULL DEFAULT NULL,
  `EstadoFinanciero` VARCHAR(120) NULL DEFAULT NULL,
  `Origen` VARCHAR(90) NULL DEFAULT NULL,
  `Profundidad` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`IdCuentaContable`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `FiscoFlex`.`TiposPolizas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `FiscoFlex`.`TiposPolizas` (
  `IdTipoPoliza` VARCHAR(4) NOT NULL,
  `Descripcion` VARCHAR(150) NULL DEFAULT NULL,
  PRIMARY KEY (`IdTipoPoliza`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `FiscoFlex`.`Polizas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `FiscoFlex`.`Polizas` (
  `IdPoliza` VARCHAR(32) NOT NULL,
  `Num` INT(11) NULL DEFAULT NULL,
  `NumNumerosMovimientos` INT(11) NULL DEFAULT NULL,
  `FechaPoliza` DATE NULL DEFAULT NULL,
  `Cargos` DECIMAL(10,0) NULL DEFAULT NULL,
  `Abonos` DECIMAL(10,0) NULL DEFAULT NULL,
  `Mayor` INT(11) NULL DEFAULT NULL,
  `Concepto` VARCHAR(255) NULL DEFAULT NULL,
  `IdTipoPoliza` VARCHAR(4) NULL DEFAULT NULL,
  PRIMARY KEY (`IdPoliza`),
  INDEX `IdTipoPoliza` (`IdTipoPoliza` ASC),
  CONSTRAINT `Polizas_ibfk_1`
    FOREIGN KEY (`IdTipoPoliza`)
    REFERENCES `FiscoFlex`.`TiposPolizas` (`IdTipoPoliza`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `FiscoFlex`.`Movimientos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `FiscoFlex`.`Movimientos` (
  `IdMovimiento` VARCHAR(32) NOT NULL,
  `Conceptos` VARCHAR(255) NULL DEFAULT NULL,
  `Cargos` DECIMAL(10,0) NULL DEFAULT NULL,
  `Abonos` DECIMAL(10,0) NULL DEFAULT NULL,
  `IdPoliza` VARCHAR(32) NULL DEFAULT NULL,
  `IdCuentaContable` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`IdMovimiento`),
  INDEX `IdPoliza` (`IdPoliza` ASC),
  INDEX `IdCuentaContable` (`IdCuentaContable` ASC),
  CONSTRAINT `Movimientos_ibfk_1`
    FOREIGN KEY (`IdPoliza`)
    REFERENCES `FiscoFlex`.`Polizas` (`IdPoliza`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `Movimientos_ibfk_2`
    FOREIGN KEY (`IdCuentaContable`)
    REFERENCES `FiscoFlex`.`CuentasContables` (`IdCuentaContable`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `FiscoFlex`.`SaldosCuentasContables`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `FiscoFlex`.`SaldosCuentasContables` (
  `IdSaldoCuentaContable` VARCHAR(32) NOT NULL,
  `Cargos` DECIMAL(10,0) NULL DEFAULT NULL,
  `Abonos` DECIMAL(10,0) NULL DEFAULT NULL,
  `AnyoFiscal` INT(11) NULL DEFAULT NULL,
  `IdCuentaContable` INT(11) NULL DEFAULT NULL,
  `mes` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`IdSaldoCuentaContable`),
  INDEX `IdCuentaContable` (`IdCuentaContable` ASC),
  CONSTRAINT `SaldosCuentasContables_ibfk_1`
    FOREIGN KEY (`IdCuentaContable`)
    REFERENCES `FiscoFlex`.`CuentasContables` (`IdCuentaContable`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `FiscoFlex`.`TiposPolizasFolios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `FiscoFlex`.`TiposPolizasFolios` (
  `IdTipoPolizaFolio` VARCHAR(4) NOT NULL,
  `Folio` INT(11) NULL DEFAULT NULL,
  `AnyoFiscal` INT(11) NULL DEFAULT NULL,
  `IdTipoPoliza` VARCHAR(4) NULL DEFAULT NULL,
  PRIMARY KEY (`IdTipoPolizaFolio`),
  INDEX `IdTipoPoliza` (`IdTipoPoliza` ASC),
  CONSTRAINT `TiposPolizasFolios_ibfk_1`
    FOREIGN KEY (`IdTipoPoliza`)
    REFERENCES `FiscoFlex`.`TiposPolizas` (`IdTipoPoliza`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `FiscoFlex`.`Usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `FiscoFlex`.`Usuarios` (
  `IdUsuario` INT(11) NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(150) NULL DEFAULT NULL,
  `Email` VARCHAR(150) NULL DEFAULT NULL,
  `Password` VARCHAR(200) NULL DEFAULT NULL,
  `Activo` TINYINT(1) NULL DEFAULT NULL,
  `IdPerfil` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`IdUsuario`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `FiscoFlex`.`Tokens`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `FiscoFlex`.`Tokens` (
  `IdToken` INT(11) NOT NULL AUTO_INCREMENT,
  `Token` VARCHAR(120) NULL DEFAULT NULL,
  `FechaCreacion` DATE NULL DEFAULT NULL,
  `FechaExpiracion` DATE NULL DEFAULT NULL,
  `IdUsuario` INT(11) NULL DEFAULT NULL,
  `Activo` TINYINT(1) NULL DEFAULT NULL,
  PRIMARY KEY (`IdToken`),
  INDEX `IdUsuario` (`IdUsuario` ASC),
  CONSTRAINT `Tokens_ibfk_1`
    FOREIGN KEY (`IdUsuario`)
    REFERENCES `FiscoFlex`.`Usuarios` (`IdUsuario`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
