-- MySQL Script generated by MySQL Workbench
-- jue 03 dic 2015 18:34:47 CST
-- Model: New Model    Version: 1.0
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema Contabilidad
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Contabilidad` DEFAULT CHARACTER SET latin1 ;
USE `Contabilidad` ;

-- -----------------------------------------------------
-- Table `Contabilidad`.`CuentasContables`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Contabilidad`.`CuentasContables` (
  `IdCuentaContable` INT(11) NOT NULL,
  `NombreCuenta` VARCHAR(50) NULL DEFAULT NULL,
  `CuentaPadre` INT(11) NULL DEFAULT NULL,
  `Naturaleza` VARCHAR(80) NULL DEFAULT NULL,
  `EstadoFinanciero` VARCHAR(120) NULL DEFAULT NULL,
  `Origen` VARCHAR(90) NULL DEFAULT NULL,
  `Profundidad` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`IdCuentaContable`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `Contabilidad`.`TiposPolizas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Contabilidad`.`TiposPolizas` (
  `IdTipoPoliza` VARCHAR(4) NOT NULL,
  `Descripcion` VARCHAR(150) NULL DEFAULT NULL,
  PRIMARY KEY (`IdTipoPoliza`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `Contabilidad`.`Polizas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Contabilidad`.`Polizas` (
  `IdPoliza` VARCHAR(32) NOT NULL,
  `Num` INT(11) NULL DEFAULT NULL,
  `NumNumerosMovimientos` INT(11) NULL DEFAULT NULL,
  `FechaPoliza` DATE NULL DEFAULT NULL,
  `Cargos` DECIMAL(10,0) NULL DEFAULT NULL,
  `Abonos` DECIMAL(10,0) NULL DEFAULT NULL,
  `Mayor` INT(11) NULL DEFAULT NULL,
  `Concepto` VARCHAR(255) NULL DEFAULT NULL,
  `IdTipoPoliza` VARCHAR(4) NULL DEFAULT NULL,
  PRIMARY KEY (`IdPoliza`),
  INDEX `IdTipoPoliza` (`IdTipoPoliza` ASC),
  CONSTRAINT `Polizas_ibfk_1`
    FOREIGN KEY (`IdTipoPoliza`)
    REFERENCES `Contabilidad`.`TiposPolizas` (`IdTipoPoliza`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `Contabilidad`.`Movimientos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Contabilidad`.`Movimientos` (
  `IdMovimiento` VARCHAR(32) NOT NULL,
  `Conceptos` VARCHAR(255) NULL DEFAULT NULL,
  `Cargos` DECIMAL(10,0) NULL DEFAULT NULL,
  `Abonos` DECIMAL(10,0) NULL DEFAULT NULL,
  `IdPoliza` VARCHAR(32) NULL DEFAULT NULL,
  `IdCuentaContable` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`IdMovimiento`),
  INDEX `IdPoliza` (`IdPoliza` ASC),
  INDEX `IdCuentaContable` (`IdCuentaContable` ASC),
  CONSTRAINT `Movimientos_ibfk_1`
    FOREIGN KEY (`IdPoliza`)
    REFERENCES `Contabilidad`.`Polizas` (`IdPoliza`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `Movimientos_ibfk_2`
    FOREIGN KEY (`IdCuentaContable`)
    REFERENCES `Contabilidad`.`CuentasContables` (`IdCuentaContable`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `Contabilidad`.`SaldosCuentasContables`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Contabilidad`.`SaldosCuentasContables` (
  `IdSaldoCuentaContable` VARCHAR(32) NOT NULL,
  `Cargos` DECIMAL(10,0) NULL DEFAULT NULL,
  `Abonos` DECIMAL(10,0) NULL DEFAULT NULL,
  `AnyoFiscal` INT(11) NULL DEFAULT NULL,
  `IdCuentaContable` INT(11) NULL DEFAULT NULL,
  `mes` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`IdSaldoCuentaContable`),
  INDEX `IdCuentaContable` (`IdCuentaContable` ASC),
  CONSTRAINT `SaldosCuentasContables_ibfk_1`
    FOREIGN KEY (`IdCuentaContable`)
    REFERENCES `Contabilidad`.`CuentasContables` (`IdCuentaContable`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `Contabilidad`.`TiposPolizasFolios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Contabilidad`.`TiposPolizasFolios` (
  `IdTipoPolizaFolio` VARCHAR(4) NOT NULL,
  `Folio` INT(11) NULL DEFAULT NULL,
  `AnyoFiscal` INT(11) NULL DEFAULT NULL,
  `IdTipoPoliza` VARCHAR(4) NULL DEFAULT NULL,
  PRIMARY KEY (`IdTipoPolizaFolio`),
  INDEX `IdTipoPoliza` (`IdTipoPoliza` ASC),
  CONSTRAINT `TiposPolizasFolios_ibfk_1`
    FOREIGN KEY (`IdTipoPoliza`)
    REFERENCES `Contabilidad`.`TiposPolizas` (`IdTipoPoliza`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
